### ISSUE TITLE
Crashes when loading mesh

### ISSUE THREAD

**Issue by willfig** [shawes/mesh3d-python#1]
Tried to run and got this error on a mesh.obj (posted on Cloudstor)

ValueError: invalid literal for int() with base 10: '963640/1916042'

StackTrace:
C:\Users\wfig7057\Dropbox\Workspace\Software\Python\mesh3d>main.py --size 2 --verbose --out "text.csv" --meshes "LI-CC_2A_OBJ.obj"
Starting to read the mesh files...
Traceback (most recent call last):
  File "C:\Users\wfig7057\Dropbox\Workspace\Software\Python\mesh3d\main.py", line 3, in <module>
    core.run()
  File "C:\Users\wfig7057\Dropbox\Workspace\Software\Python\mesh3d\mesh3d\core.py", line 124, in run
    meshes = _read_in_meshes(args)
  File "C:\Users\wfig7057\Dropbox\Workspace\Software\Python\mesh3d\mesh3d\core.py", line 26, in _read_in_meshes
    meshes = map(lambda x: read_obj(x, args.verbose, DimensionOrder(args.dim)), args.meshes)
  File "C:\Users\wfig7057\Dropbox\Workspace\Software\Python\mesh3d\mesh3d\core.py", line 26, in <lambda>
    meshes = map(lambda x: read_obj(x, args.verbose, DimensionOrder(args.dim)), args.meshes)
  File "C:\Users\wfig7057\Dropbox\Workspace\Software\Python\mesh3d\mesh3d\mesh_io.py", line 19, in read_obj
    faces.append(_create_face(instructions, vertices))
  File "C:\Users\wfig7057\Dropbox\Workspace\Software\Python\mesh3d\mesh3d\mesh_io.py", line 46, in _create_face
    face_recipe = (int(vertex1_index), int(vertex2_index), int(vertex3_index))
**ValueError: invalid literal for int() with base 10: '963640/1916042'**

**Comment by shawes** [comment]
Fixed to now accommodate the full specification for .OBJ files.
